<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SLB-3MVR3Q3" failures="0" tests="1" name="StepDefinition.TestRunner2" time="0.055" errors="1" timestamp="2024-04-24T14:40:29 IST" skipped="0">
  <testcase classname="StepDefinition.TestRunner2" name="setUpClass" time="0.055">
    <error message="Couldn&#039;t create a file output stream for &#039;target\rerun.txt&#039;.
Make sure the the file isn&#039;t a directory.

Note: This usually happens when plugins write to colliding paths.
For example: &#039;json:target/cucumber/report.json, html:target/cucumber&#039;
You can fix this by making the paths do no collide.
For example: &#039;json:target/cucumber/report.json, html:target/cucumber/report.html&#039;
The details are in the stack trace below:" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Couldn't create a file output stream for 'target\rerun.txt'.
Make sure the the file isn't a directory.

Note: This usually happens when plugins write to colliding paths.
For example: 'json:target/cucumber/report.json, html:target/cucumber'
You can fix this by making the paths do no collide.
For example: 'json:target/cucumber/report.json, html:target/cucumber/report.html'
The details are in the stack trace below:
at io.cucumber.core.plugin.PluginFactory.createFileOutputStream(PluginFactory.java:240)
at io.cucumber.core.plugin.PluginFactory.openStream(PluginFactory.java:199)
at io.cucumber.core.plugin.PluginFactory.convert(PluginFactory.java:166)
at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:99)
at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
at io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:92)
at io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.io.FileNotFoundException: target\rerun.txt (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
at io.cucumber.core.plugin.PluginFactory.createFileOutputStream(PluginFactory.java:237)
... 26 more
]]>
    </error>
  </testcase> <!-- setUpClass -->
  <system-out/>
</testsuite> <!-- StepDefinition.TestRunner2 -->
